### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by marcusvbda** [marcusvbda/vstack#1]
- [x] bar chart
- [x] field belongsToMany no cadastro e edição
- [x] field hasMany no cadastro e edição
- [x] field upload
- [x] relatorio de importação de csv
- [x] obejct e array field
- [x] audit
